apiVersion: v1
kind: Service
metadata:
  name: helm-sphere-auth
  labels:
    run: helm-sphere-auth
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: helm-sphere-auth